pub mod topbar;
pub use ermete_dock::ui as dock;
pub mod control_center;
pub mod notifications;
pub mod osd;
pub mod powermenu;
pub mod spotlight;
pub mod clipboard;
pub mod gatekeeper_prompt;
pub mod privacy_prompt;
pub mod mission_control;
pub mod desktop_widgets;
pub mod store;
