[workspace]
members = [
    "forge/specs/ermete-backup/ermete-backup-1.0.0",
    "forge/specs/ermete-cloud-rs/ermete-cloud-rs-1.0.0",
    "forge/specs/ermete-daemon-rs/ermete-daemon-rs-0.2.1",
    "forge/specs/ermete-dock/ermete-dock-1.0.0",
    "forge/specs/ermete-doctor/ermete-doctor-1.0.0",
    "forge/specs/ermete-gatekeeper-rs/ermete-gatekeeper-rs-1.0.0",
    "forge/specs/ermete-lvfs-rs/ermete-lvfs-rs-1.0.0",
    "forge/specs/ermete-mdm-rs/ermete-mdm-rs-1.0.0",
    "forge/specs/ermete-mesh-sync/ermete-mesh-sync-1.0.0",
    "forge/specs/ermete-recovery/ermete-recovery-1.0.0",
    "forge/specs/ermete-settings-rs/ermete-settings-rs-1.0.0",
    "forge/specs/ermete-shell-rs/ermete-shell-rs-1.0.0",
    "forge/specs/ermete-store-rs/ermete-store-rs-1.0.0",
    "forge/specs/ermete-sysmon-ebpf/ermete-sysmon-ebpf-1.0.0",
    "forge/specs/ermete-xdg-desktop-portal-ermete/xdg-desktop-portal-ermete-1.0.0",
    "forge/specs/ermete-ai-daemon/ermete-ai-daemon-1.0.0",
    "forge/specs/ermete-style",
    "forge/specs/ermete-niri-ipc",
    "forge/specs/ermete-live-patcher/ermete-live-patcher-1.0.0",
    "forge/specs/ermete-daemon-patch-plugin",
    "system/confidential_computing/ermete-attestation",
    "system/ebpf/ebpf-core",
    "system/ebpf/ebpf-loader",
    "system/ermete-agentic-kernel",
    "system/ermete-audio-bus",
    "system/ermete-cluster-mesh",
    "system/ermete-compositor",
    "system/ermete-ebpf-sched",
    "system/ermete-greeter",
    "system/ermete-hypervisor-daemon",
    "system/ermete-init-oracle",
    "system/ermete-kernel-forge",
    "system/ermete-mesh-bus",
    "system/ermete-net-unikernel",
    "system/ermete-self-evolution",
    "system/ermete-semantic-db",
    "system/ermete-store",
    "system/ermete-telemetry",
    "system/unikernel"
]

exclude = [
    "tests/fuzz"
]


resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package.ermete-ai-daemon]
opt-level = 3
