[package]
name = "ermete-gatekeeper-rs"
version = "1.0.0"
edition = "2021"

[lib]
name = "ermete_gatekeeper_rs"
path = "src/lib.rs"

[[bin]]
name = "ermete-gatekeeper-rs"
path = "src/main.rs"

[dependencies]
libc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
xattr = "1.0"
pqc_dilithium = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }



[features]
default = ["std"]
std = []
scudo_ffi = []
