pub mod physics;
pub mod render;

pub use physics::{spring_physics_system, spring_physics_system_batch, DT_1000HZ};

use crate::ecs::components::{
    Geometry, PhysicsSpring, Position, RenderLayer, Velocity, WaylandSurface,
};
use crate::ecs::entity::Entity;
use crate::ecs::world::SharedEcsWorld;
use anyhow::Result;
use serde::{Deserialize, Serialize};

/// High-frequency Mass-Spring-Damper Physics System for 1000Hz smooth Wayland frame ticks.
/// Integrates velocity and spring forces towards target coordinates.
pub fn physics_system(world: &SharedEcsWorld, dt: f32) -> Result<()> {
    let mut world_guard = world.write()?;
    let dt_clamped = dt.min(0.05); // Numerical stability cap

    // Collect list of entities with Position and Velocity
    let entities: Vec<Entity> = world_guard
        .query_2::<Position, Velocity>()
        .into_iter()
        .map(|(e, _, _)| e)
        .collect();

    for entity in entities {
        // Evaluate spring force if PhysicsSpring component is present
        if let (Some(pos), Some(vel), Some(spring)) = (
            world_guard.get_component::<Position>(entity).cloned(),
            world_guard.get_component::<Velocity>(entity).cloned(),
            world_guard.get_component::<PhysicsSpring>(entity).cloned(),
        ) {
            let dx = pos.x - spring.target_x;
            let dy = pos.y - spring.target_y;

            // F = -k * dx - c * vx
            let fx = -spring.stiffness * dx - spring.damping * vel.vx;
            let fy = -spring.stiffness * dy - spring.damping * vel.vy;

            let ax = fx / spring.mass.max(0.001);
            let ay = fy / spring.mass.max(0.001);

            let new_vx = vel.vx + ax * dt_clamped;
            let new_vy = vel.vy + ay * dt_clamped;

            let new_x = pos.x + new_vx * dt_clamped;
            let new_y = pos.y + new_vy * dt_clamped;

            if let Some(p) = world_guard.get_component_mut::<Position>(entity) {
                p.x = new_x;
                p.y = new_y;
            }
            if let Some(v) = world_guard.get_component_mut::<Velocity>(entity) {
                v.vx = new_vx;
                v.vy = new_vy;
            }
        } else {
            // Euler velocity integration
            if let (Some(pos), Some(vel)) = (
                world_guard.get_component::<Position>(entity).cloned(),
                world_guard.get_component::<Velocity>(entity).cloned(),
            ) {
                if let Some(p) = world_guard.get_component_mut::<Position>(entity) {
                    p.x += vel.vx * dt_clamped;
                    p.y += vel.vy * dt_clamped;
                }
            }
        }
    }

    Ok(())
}

/// Render Draw Call descriptor generated by the Render Sorting System for GPU scanout.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenderEntityCall {
    pub entity: Entity,
    pub surface_id: u64,
    pub app_id: String,
    pub wl_title: String,
    pub position: Position,
    pub geometry: Geometry,
    pub render_layer: RenderLayer,
    pub dma_buf_fd: Option<i32>,
    pub is_damaged: bool,
}

/// Zero-latency Render Sorting System.
/// Queries all visible entities, extracts position, geometry, render layer, and surface handles,
/// then sorts them by layer depth (LayerType, z-index).
pub fn render_sort_system(world: &SharedEcsWorld) -> Result<Vec<RenderEntityCall>> {
    let world_guard = world.read()?;
    let query_results =
        world_guard.query_4::<Position, Geometry, RenderLayer, WaylandSurface>();

    let mut draw_calls: Vec<RenderEntityCall> = query_results
        .into_iter()
        .filter(|(_, _, _, layer, _)| layer.is_visible())
        .map(|(entity, pos, geom, layer, surface)| RenderEntityCall {
            entity,
            surface_id: surface.surface_id,
            app_id: surface.app_id.clone(),
            wl_title: surface.wl_title.clone(),
            position: *pos,
            geometry: *geom,
            render_layer: *layer,
            dma_buf_fd: surface.dma_buf_fd,
            is_damaged: surface.is_damaged,
        })
        .collect();

    // Sort by LayerType composite depth key (LayerType first, then z-index)
    draw_calls.sort_by_key(|call| call.render_layer.composite_depth_key());

    Ok(draw_calls)
}

/// Damage Tracking System.
/// Identifies damaged Wayland surfaces, collects surface IDs for DRM plane updates, and clears dirty damage flags.
pub fn damage_tracking_system(world: &SharedEcsWorld) -> Result<Vec<u64>> {
    let mut world_guard = world.write()?;
    let entities: Vec<Entity> = world_guard
        .query_1::<WaylandSurface>()
        .into_iter()
        .filter(|(_, s)| s.is_damaged)
        .map(|(e, _)| e)
        .collect();

    let mut damaged_surfaces = Vec::with_capacity(entities.len());

    for entity in entities {
        if let Some(surface) = world_guard.get_component_mut::<WaylandSurface>(entity) {
            damaged_surfaces.push(surface.surface_id);
            surface.clear_damage();
        }
    }

    Ok(damaged_surfaces)
}

