[package]
name = "ermete-store-rs"
version = "1.0.0"
edition = "2021"
description = "Ermete OS Universal App Store Daemon (Flatpak/OCI)"

[dependencies]
mimalloc = { version = "0.1", default-features = false }
ermete-style = { path = "../../ermete-style" }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
gtk4 = "0.7"
relm4 = "0.7"
zbus = { version = "5.18.0", features = ["tokio"] }


