[package]
name = "ermete-cloud-rs"
version = "1.0.0"
edition = "2021"
description = "Ermete OS Continuity & Local P2P Sync Daemon"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
zbus = "4.4.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[target.'cfg(not(target_os = "hermit"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }


