[package]
name = "ermete-cloud-rs"
version = "1.0.0"
edition = "2021"
description = "Ermete OS Continuity & Local P2P Sync Daemon"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
zbus = "4.4.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
pqc_kyber = { version = "0.7.1", features = ["kyber1024"] }
pqc_dilithium = "0.2.0"
rand_core = "0.6"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }



[target.'cfg(not(target_os = "hermit"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }


