[package]
name = "ermete-shell-rs"
version = "1.0.0"
edition = "2021"
authors = ["Ermete Forge <forge@ermete.os>"]
description = "Pure Rust native shell for Ermete OS"

[dependencies]
mimalloc = { version = "0.1", default-features = false }
gtk4 = "0.7"
gtk4-layer-shell = "0.2"
glib = "0.18"
chrono = "0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.120"
zbus = "4.4.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "net", "rt", "sync", "time"] }
notify = "6.1.1"
clap = { version = "4.6.1", features = ["derive"] }
greetd_ipc = "0.10.3"
meval = "0.2"
relm4 = "0.7"
landlock = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

arc-swap = "1.6"

# Decoupled domain crates
ermete-dock = { path = "../../ermete-dock/ermete-dock-1.0.0" }

ermete-style = { path = "../../ermete-style" }
ermete-niri-ipc = { version = "0.1.0", path = "../../ermete-niri-ipc" }

