[package]
name = "ermete-settings-rs"
version = "1.0.0"
edition = "2021"
authors = ["Ermete Forge <forge@ermete.os>"]
description = "Pure Rust native System Settings for Ermete OS"

[dependencies]
mimalloc = { workspace = true }
gtk4 = { workspace = true }
glib = { workspace = true }
zbus = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rustix = { version = "0.38", features = ["process"] }
relm4 = { workspace = true }
anyhow = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ermete-style = { path = "../../../../system/ermete-style" }
ermete-niri-ipc = { version = "0.1.0", path = "../../ermete-niri-ipc" }



