[build]
rustflags = [
    "-D", "unsafe_code",
    "-W", "clippy::undocumented_unsafe_blocks",
    "-W", "clippy::multiple_unsafe_ops_per_block",
]

[target.'cfg(all())']
rustflags = [
    "-D", "unsafe_code",
    "-W", "clippy::undocumented_unsafe_blocks",
    "-W", "clippy::multiple_unsafe_ops_per_block",
]
