export image_name := env("IMAGE_NAME", "ermete")
export default_tag := env("DEFAULT_TAG", "latest")
export bib_image := env("BIB_IMAGE", "quay.io/centos-bootc/bootc-image-builder:latest")

[private]
default:
    @just --list

# Check Just Syntax
[group('Just')]
check:
    just --unstable --fmt --check -f Justfile

# Fix Just Syntax
[group('Just')]
fix:
    just --unstable --fmt -f Justfile

# Clean Repo Build Artifacts
[group('Utility')]
clean:
    rm -rf *_build* previous.manifest.json changelog.md output.env output/

# Build OS Container Image
build target_image=image_name tag=default_tag:
    #!/usr/bin/env bash
    BUILD_ARGS=()
    if [[ -z "$(git status -s)" ]]; then
        BUILD_ARGS+=("--build-arg" "SHA_HEAD_SHORT=$(git rev-parse --short HEAD)")
    fi
    podman build "${BUILD_ARGS[@]}" --pull=newer --tag "${target_image}:${tag}" .

_build-bib target_image tag type:
    #!/usr/bin/env bash
    set -euo pipefail
    config="disk_config/disk.toml"
    if [[ "${type}" == "iso" ]]; then
        config="disk_config/iso.toml"
    fi
    BUILDTMP=$(mktemp -d -t _build-bib.XXXXXXXXXX)
    sudo podman run --rm -it --privileged --pull=newer --net=host \
      --security-opt label=type:unconfined_t \
      -v "$(pwd)/${config}:/config.toml:ro" \
      -v "$BUILDTMP:/output" \
      -v /var/lib/containers/storage:/var/lib/containers/storage \
      "${bib_image}" --type "${type}" --use-librepo=True --rootfs=btrfs --config /config.toml \
      "${target_image}:${tag}"

    if [[ "${type}" == "qcow2" ]]; then
        sudo qemu-img convert -f qcow2 -O vhdx "$BUILDTMP/qcow2/disk.qcow2" "$BUILDTMP/disk.vhdx"
    fi
    mkdir -p output
    sudo mv -f "$BUILDTMP"/* output/
    sudo rmdir "$BUILDTMP"
    sudo chown -R $USER:$USER output/

# Build Virtual Machine Image (qcow2 / iso)
[group('Build VM Image')]
build-vm type="qcow2" target_image=("localhost/" + image_name) tag=default_tag:
    just _build-bib "{{ target_image }}" "{{ tag }}" "{{ type }}"

# Runs shellcheck on all Bash scripts
lint:
    #!/usr/bin/env bash
    set -euo pipefail
    find . -iname "*.sh" -type f -exec shellcheck "{}" +

# Runs shfmt on all Bash scripts
format:
    #!/usr/bin/env bash
    set -euo pipefail
    find . -iname "*.sh" -type f -exec shfmt --write "{}" +
