[package]
name = "ermete-backup"
version = "1.0.0"
edition = "2021"
authors = ["Ermete Forge <forge@ermete.os>"]
description = "Instant Bcachefs Home Snapshot Manager & Time Machine GUI for Ermete OS"
license = "MIT"

[[bin]]
name = "ermete-backup-daemon"
path = "src/daemon.rs"


[dependencies]
dirs = "5.0"
glib = { workspace = true }
zbus = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["full"] }
libc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = "0.4"



