[package]
name = "ermete-lvfs-rs"
version = "1.0.0"
edition = "2021"
description = "Ermete OS Firmware & LVFS Automation Daemon"

[dependencies]
mimalloc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }


