[package]
name = "ermete-dock"
version = "1.0.0"
edition = "2021"
authors = ["Ermete Forge <forge@ermete.os>"]
description = "Visual Dock and taskbar application logic for Ermete OS"

[dependencies]
gtk4 = { workspace = true }
gtk4-layer-shell = { workspace = true }
glib = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
notify = "6.1.1"
ermete-style = { path = "../../ermete-style" }
ermete-niri-ipc = { path = "../../ermete-niri-ipc" }
tokio = { workspace = true, features = ["full"] }

