[package]
name = "ermete-daemon-rs"
version = "0.2.1"
edition = "2021"

[dependencies]
mimalloc = { version = "0.1", default-features = false }
zbus = { version = "5.17.0", features = ["tokio"] }
zbus_polkit = "5.0"
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.120"
futures-util = "0.3.30"
libc = "0.2"
chacha20poly1305 = "0.10"
rand = "0.8"
hkdf = "0.12"
sha2 = "0.10"
tracing = "0.1"

# Decoupled domain crates
ermete-auth = { path = "../../ermete-auth/ermete-auth-1.0.0" }

