[package]
name = "ermete-mesh-sync"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
zbus = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
boringtun = "0.7"
x25519-dalek = "2.0.1"
base64 = "0.21"
rand_core = "0.6"
pqc_kyber = { workspace = true, features = ["kyber1024"] }
pqc_dilithium = { workspace = true }
ermete-bus-api = { path = "../../../../system/ermete-bus-api" }


