[package]
name = "ebpf-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { workspace = true }
aya-log = "0.3.0"
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal", "time"] }
env_logger = { workspace = true }
log = "0.4"
anyhow = { workspace = true }
libc = { workspace = true }



[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"
