name: Test Env
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Env
        run: |
          podman run --runtime=runc -i --rm --security-opt label=disable --security-opt seccomp=unconfined --privileged \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/hr-mes/ermete-os-builder:latest \
            bash -c 'env'
